WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET VERIFY OFF;
BEGIN
  HM_DM_WRK_OWNER.ETL_TRUNCATE('WRK_SAE_OUT');
  HM_DM_WRK_OWNER.ETL_TRUNCATE('WRK_SAFETY_OUT');
  HM_DM_WRK_OWNER.ETL_TRUNCATE('WRK_PD_OUT');
  HM_DM_WRK_OWNER.ETL_TRUNCATE('WRK_PD_OUT_HIST');
  HM_DM_WRK_OWNER.ETL_TRUNCATE('WRK_TL_OUT');
  HM_DM_WRK_OWNER.ETL_TRUNCATE('WRK_RT_OUT');
  HM_DM_WRK_OWNER.ETL_TRUNCATE('WRK_RT_OUT_HIST');
  HM_DM_WRK_OWNER.ETL_TRUNCATE('WRK_MI_OUT');
  HM_DM_WRK_OWNER.ETL_TRUNCATE('WRK_GL_OUT_OVERVIEW');
END;
/
EXIT;
