#!/bin/bash

########################################################################
# Name:        R_Status_Check.sh
#
# Description: Script to send status mail based on  R return value     
# Notes:     o This is used to send status mail based on staus value present in the 
#              indicator file after each Module execution completes
#              value SUCCESS in indicator file implies module succeeded,
#              Value ERROR in indicator file implies module had ERRORS 
#              WARNING in indicator file implies module had WARNING
#            
#
# Author:      Rajesh Mechery
# Date:        2016-10-26
# Version : 0.1
########################################################################


##############################################################################
# set  variables
#########################################################################

export log_file=`ls -alt /app/r/engine/Log/Log* | head -1 | sed 's/:[0-9][0-9]/,/' |  tr -d ' \t\n\r\f' | cut -d',' -f2`

dat=`date +%d-%m-%Y_%H:%M:%S` 

SA_success_count=0
SA_WARNING_count=0
SA_ERROR_count=0


SH_success_count=0
SH_WARNING_count=0
SH_ERROR_count=0




PD_success_count=0
PD_WARNING_count=0
PD_ERROR_count=0


TL_success_count=0
TL_WARNING_count=0
TL_ERROR_count=0


RT_success_count=0
RT_WARNING_count=0
RT_ERROR_count=0


# take sucess , warning and error counts for each module based on the indicator file generated by R Modules


if [ -f $R_dir/SA.ind ]; then

SA_success_count=`grep SUCCESS $R_dir/SA.ind | wc -l`
SA_WARNING_count=`grep NON $R_dir/SA.ind | wc -l`
SA_ERROR_count=`grep ERROR $R_dir/SA.ind | wc -l`

fi

echo $SA_success_count $SA_WARNING_count $SA_ERROR_count


if [ -f $R_dir/SH.ind ]; then

SH_success_count=`grep SUCCESS $R_dir/SH.ind | wc -l`
SH_WARNING_count=`grep NON $R_dir/SH.ind | wc -l`
SH_ERROR_count=`grep ERROR $R_dir/SH.ind | wc -l`

fi

echo $SH_success_count $SH_WARNING_count $SH_ERROR_count


if [ -f $R_dir/PD.ind ]; then

PD_success_count=`grep SUCCESS $R_dir/PD.ind | wc -l`
PD_WARNING_count=`grep NON $R_dir/PD.ind | wc -l`
PD_ERROR_count=`grep ERROR $R_dir/PD.ind | wc -l`

fi

echo $PD_success_count $PD_WARNING_count $PD_ERROR_count

if [ -f $R_dir/TL.ind ]; then


TL_success_count=`grep SUCCESS $R_dir/TL.ind | wc -l`
TL_WARNING_count=`grep NON $R_dir/TL.ind | wc -l`
TL_ERROR_count=`grep ERROR $R_dir/TL.ind | wc -l`

fi

echo $TL_success_count $TL_WARNING_count $TL_ERROR_count


if [ -f $R_dir/TO.ind ]; then


RT_success_count=`grep SUCCESS $R_dir/TO.ind | wc -l`
RT_WARNING_count=`grep NON $R_dir/TO.ind | wc -l`
RT_ERROR_count=`grep ERROR $R_dir/TO.ind | wc -l`

fi

echo $RT_success_count $RT_WARNING_count $RT_ERROR_count


count_success=`expr $SA_success_count + $SH_success_count +  $PD_success_count + $TL_success_count + $RT_success_count`



count_warning=`expr $SA_WARNING_count + $SH_WARNING_count +  $PD_WARNING_count + $TL_WARNING_count + $RT_WARNING_count`


count_error=`expr $SA_ERROR_count + $SH_ERROR_count + $PD_ERROR_count + $TL_ERROR_count + $RT_ERROR_count`

cd $R_dir




# if all modules have error then send out a mail saying R Mail call failed and attach log file


if [ $SH_ERROR_count -eq 1  -a $SA_ERROR_count -eq 1  -a $PD_ERROR_count -eq 1 -a $TL_ERROR_count -eq 1  -a $RT_ERROR_count -eq 1 ]; then


        echo  "Dear Recipient:"  > $bdy_fail
        printf  "\n" >> $bdy_fail
        echo  "R call failed, please find attached R log file" >> $bdy_fail


         cat  $bdy_fail | mailx -s "R call failed on $dat" -a $log_file ${mail_recp_bus}


     exit 1    

fi        


if [ $count_warning -gt 0 -o $count_error -gt 0 ]; then

# if some modules have error or warning then send out a mail saying R call completed with errors and attach log file 
  

         echo "Dear Recipient:" > $bdy_succ
         printf  "\n" >> $bdy_succ
         echo "R call completed with errors and warnings, please find attached R log file" >> $bdy_succ



         cat  $bdy_succ | mailx -s "R call completed with errors and warnings on $dat" -a $log_file   ${mail_recp_bus}

 fi 

# if none of the modules have error or warning then send out a mail saying R call completed with no errors and attach log file and bench mark file

if [ $SH_ERROR_count -eq 0  -a $SA_ERROR_count -eq 0  -a $PD_ERROR_count -eq 0 -a $TL_ERROR_count -eq 0  -a $RT_ERROR_count -eq 0 ]; then

       echo  "Dear Recipient:"  > $bdy_succ
       printf  "\n" >> $bdy_succ
       echo  "R call completed successfully, please find attached R log file " >> $bdy_succ
       printf  "\n" >> $bdy_succ
       
  

        cat  $bdy_succ | mailx -s "R call completed successfully on $dat" -a $log_file  ${mail_recp_bus} 

fi





